"""Offline provisioning contract for the V2 code-semantic model.

The package deliberately has no HTTP, hub, inference, or query-path
dependency.  It validates a caller-supplied directory of immutable bytes and
publishes that directory atomically.
"""

from .provisioning import (
    EXPECTED_ARTIFACT_DIGEST,
    EXPECTED_DIMENSIONS,
    EXPECTED_MAX_LENGTH,
    EXPECTED_MODEL,
    EXPECTED_REVISION,
    MANIFEST_SCHEMA,
    RECEIPT_SCHEMA,
    JOURNAL_SCHEMA,
    UNINSTALL_JOURNAL_SCHEMA,
    DirectoryVerification,
    InstallResult,
    JournalValidationError,
    ManifestValidationError,
    ModelManifest,
    ReceiptValidationError,
    SemanticProvisioningError,
    SimulatedInterruption,
    UnsafePathError,
    VerificationError,
    artifact_digest,
    canonical_json,
    install_offline,
    journal_path_for,
    load_manifest,
    load_receipt,
    manifest_digest,
    parse_manifest,
    receipt_path_for,
    recover_install,
    recover_uninstall,
    rollback,
    rollback_install,
    rollback_path_for,
    rollback_receipt_path_for,
    staging_path_for,
    uninstall,
    uninstall_journal_path_for,
    uninstall_offline,
    removal_journal_path_for,
    validate_receipt,
    verify_directory,
    verify_installation,
)

__all__ = [
    "EXPECTED_ARTIFACT_DIGEST",
    "EXPECTED_DIMENSIONS",
    "EXPECTED_MAX_LENGTH",
    "EXPECTED_MODEL",
    "EXPECTED_REVISION",
    "MANIFEST_SCHEMA",
    "RECEIPT_SCHEMA",
    "JOURNAL_SCHEMA",
    "UNINSTALL_JOURNAL_SCHEMA",
    "DirectoryVerification",
    "InstallResult",
    "JournalValidationError",
    "ManifestValidationError",
    "ModelManifest",
    "ReceiptValidationError",
    "SemanticProvisioningError",
    "SimulatedInterruption",
    "UnsafePathError",
    "VerificationError",
    "artifact_digest",
    "canonical_json",
    "install_offline",
    "journal_path_for",
    "load_manifest",
    "load_receipt",
    "manifest_digest",
    "parse_manifest",
    "receipt_path_for",
    "recover_install",
    "recover_uninstall",
    "rollback",
    "rollback_install",
    "rollback_path_for",
    "rollback_receipt_path_for",
    "staging_path_for",
    "uninstall",
    "uninstall_journal_path_for",
    "uninstall_offline",
    "removal_journal_path_for",
    "validate_receipt",
    "verify_directory",
    "verify_installation",
]
